services:

  php_laravel:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php_laravel
    volumes:
      - ./:/var/www
    networks:
      - website2
    environment:
      PHP_IDE_CONFIG: serverName=Docker # For Xdebug
    restart: unless-stopped

  nginx_laravel:
    image: nginx
    container_name: nginx_laravel
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_laravel
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx_laravel.tls=true
      - traefik.http.routers.nginx_laravel.rule=Host(`${NGINX_HOST}`) || Host(`${NGINX_HOST_WWW}`)
      - traefik.http.routers.nginx_laravel.entrypoints=websecure
      - traefik.http.services.nginx_laravel.loadbalancer.server.port=80
      # redirect www to non-www
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.nginx_laravel.middlewares=mywwwredirect
    networks:
      - website2

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: $DB_PASSWORD
      MARIADB_DATABASE: $DB_DATABASE
      MARIADB_USER: $DB_USERNAME
      MARIADB_PASSWORD: $DB_PASSWORD
      APP_DB_HOST: $ADMINER_HOST
      APP_DB_USER: $DB_USERNAME
      APP_DB_PASSWD: $DB_PASSWORD
    volumes:
      - ./dbdata:/var/lib/mysql
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mariadb.rule=HostSNI(`*`)
      - traefik.tcp.services.mariadb.loadbalancer.server.port=3306
      - traefik.tcp.routers.mariadb.entrypoints=mariadb
    networks:
      - website2

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.tls=true
      - traefik.http.routers.adminer.rule=Host(`${ADMINER_HOST}`)
      - traefik.http.routers.adminer.entrypoints=websecure
    depends_on:
      - mariadb
    networks:
      - website2

networks:
  website2:
    name: "proxy"
    external: true

